version: "2"

services:
  nginx:
    build: ../services/nginx
    ports:
      - "8081:80"
    links:
      - webapp
      - mqtt
    depends_on:
      - webapp
      - mqtt
    external_links: 
      - mqtt:9001

  # Mosquitto
  # For testing outside
  mqtt:
    build: ../services/mqtt
    command: mosquitto -c /etc/mosquitto/mosquitto.conf
    ports:
      - 11883:1883  # mosquito_pub -h localhost -p 11883
      - 9001
  webapp:
    build: ../services/webapp
    volumes:
      - '../services/webapp/src:/home/webapp/src'
    command: "venv/bin/python src/main.py"
